[package]
name = "jr-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
jr-base.workspace = true
jr-diag.workspace = true
jr-db.workspace = true
jr-link.workspace = true
jr-vm.workspace = true
tempfile = "3"
