[package]
name = "jr-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "jr"
path = "src/main.rs"

[lib]
name = "jr_cli"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
jr-base.workspace = true
jr-diag.workspace = true
jr-db.workspace = true
jr-hir.workspace = true
jr-syntax.workspace = true
jr-fmt.workspace = true
clap.workspace = true
anyhow.workspace = true
tempfile = "3"

[dev-dependencies]
tempfile = "3"
