#!/usr/bin/env bash
# Generates `languages/jairs/highlights.scm` from the one in `tree-sitter-jairs/queries/`.
#
# # Why this is generated and not written
#
# The two editors need the *same* query over the *same* grammar in two dialects. Neovim's
# `highlights.scm` is the source of truth — it is the one gate 6 validates and the one thirteen waves
# of grammar work have kept current. Hand-copying it into `editors/zed/` would be a second answer to
# "which node is a keyword", and the copy would go stale the first time a keyword became real
# (which, per that file's own comments, has happened seven times).
#
# So the structure is shared and only the dialect is translated. The output is committed, and gate 6
# regenerates it and checks for drift — the same arrangement that keeps `src/parser.c` honest
# (ADR-0199 §12).
#
# # What actually differs between the dialects
#
# Zed's theme capture vocabulary is flatter than Neovim's, and its query engine has no
# `#lua-match?`. Both are translated below; anything not in Zed's documented capture list simply
# would not be styled, which is a silent loss of colour rather than an error.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source_query="$here/../../tree-sitter-jairs/queries/highlights.scm"
target="$here/languages/jairs/highlights.scm"

if [[ ! -f "$source_query" ]]; then
  echo "generate-queries.sh: missing $source_query" >&2
  exit 1
fi

{
  cat <<'HEADER'
; GENERATED by editors/zed/generate-queries.sh — do not edit.
;
; Source: tree-sitter-jairs/queries/highlights.scm, translated into Zed's dialect. Edit the source
; and re-run the script; gate 6 regenerates this and fails on drift, so the two cannot disagree.
;
; The translation is a capture rename plus one predicate rename:
;
;   @comment.documentation  -> @comment.doc          Zed's spelling for a doc comment.
;   @keyword.directive      -> @keyword              Zed has no keyword subtypes.
;   @keyword.type           -> @keyword
;   @keyword.import         -> @keyword
;   @function.call          -> @function             Zed styles a call as a function.
;   @number.float           -> @number               Zed has one number capture.
;   @string.special.path    -> @string.special
;   #lua-match?             -> #match?               Zed's engine is regex, not Lua patterns.
;
; Everything else — @comment @boolean @constant @constant.builtin @label @operator @property
; @punctuation.bracket @punctuation.delimiter @punctuation.special @string @type @variable
; @variable.parameter @number @function @keyword — is in Zed's documented list already.

HEADER
  sed \
    -e 's/@comment\.documentation/@comment.doc/g' \
    -e 's/@keyword\.directive/@keyword/g' \
    -e 's/@keyword\.type/@keyword/g' \
    -e 's/@keyword\.import/@keyword/g' \
    -e 's/@function\.call/@function/g' \
    -e 's/@number\.float/@number/g' \
    -e 's/@string\.special\.path/@string.special/g' \
    -e 's/#lua-match?/#match?/g' \
    "$source_query"
} >"$target"

echo "generate-queries.sh: wrote $target"
