[package]
name = "jr-pool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
jr-base.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
jr-base.workspace = true
