[package]
name = "jr-sema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
jr-base.workspace = true
jr-diag.workspace = true
jr-hir.workspace = true
jr-pool.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
jr-syntax.workspace = true
