[package]
name = "jr-diag"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
jr-base.workspace = true
annotate-snippets.workspace = true

[dev-dependencies]
expect-test.workspace = true
