[package]
name = "jr-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
jr-base.workspace = true
jr-hir.workspace = true
jr-mir.workspace = true
jr-pool.workspace = true
jr-sema.workspace = true
rustc-hash.workspace = true
libffi.workspace = true
libloading.workspace = true

[dev-dependencies]
jr-diag.workspace = true
jr-syntax.workspace = true
